title: Christian R. Hernandez
logo: assets/images/chrish47_image2.jpg
description: <strong>Data Enthusiast</strong>
show_downloads: true
theme: jekyll-theme-minimal

#exclude: ["custom.css"]
## Link to custom stylesheet
#include:
#  - assets/css/custom.css

#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

